### ISSUE TITLE
Duplicate Config classes

### ISSUE THREAD

**Issue by jonesse3** [JDACS4C-IMPROVE/IMPROVE#181]
We need to choose/merge the two different configs. We shouldn't have 2 instances of the same class. 

We have https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/improvelib/initializer/config.py that's being used in drug response prediction. 

And we have https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/workflows/lib/config/base.py that is now being called in deephyper and CSA. 

@adpartin @wilke This is highly redundant and needs to be given high priority.

**Comment by adpartin** [comment]
@jonesse3 I see that the entire dir `https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/workflows/lib/config` has been removed. Should we close this issue?

**Comment by jonesse3** [comment]
I don't understand. I see that the config folder was moved out of improvelib to workflows. 

It's still here: https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/workflows/lib/config

**Comment by adpartin** [comment]
@wilke You moved `config` from `improvelib` to `workflows`. @nkoussa was using it deephyper. How these are different?
- https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/improvelib/initializer/config.py
- https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/workflows/lib/config/base.py

**Comment by jonesse3** [comment]
Current hierachy. Expected behavior would be for workflows to use SectionConfig. 

Config Class ([initializer/config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/initializer/config.py))
   *  SectionConfig Class ([initializer/stage_config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/initializer/stage_config.py))
        *  PreprocessConfig Class ([initializer/stage_config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/initializer/stage_config.py))
          * DRPPreprocessConfig Class ([applications/drug_response_prediction/config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/applications/drug_response_prediction/config.py))
       * TrainConfig Class ([initializer/stage_config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/initializer/stage_config.py))
             * DRPTrainConfig Class ([applications/drug_response_prediction/config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/applications/drug_response_prediction/config.py))
       *  InferConfig Class ([initializer/stage_config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/initializer/stage_config.py))
                *  DRPInferConfig Class ([applications/drug_response_prediction/config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/applications/drug_response_prediction/config.py))

**Comment by wilke** [comment]
As discussed on Slack, the config directory is not used in any of the improvelib modules or the model codes. This code is not part of the documentation. 

This config is to support workflows and as wanted by Alex no workflow code or functionality should be in improvelib, especially if we have to make modifications to it.  The workflow codes should not depend on the improvelib code and not require modifications to improvelib. The SectionConfig is the wrong module since its purpose is for the controlled stages of Preprocessing, Training and Infer and "users" should not be required to modify code in there to match their requirements. 

I see two solutions,

a) Create a completely  independent config for the workflows, as already implemented with the config dir
b) Create a workflow-specific  config in the workflow code and inherit from the base config ([initializer/config.py](https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/natasha/deephyper-initial/improvelib/initializer/config.py))

**Comment by nkoussa** [comment]
I don't like (a) and for (b) I don't think we need a workflow-specific config (e.g. `HPOConfig`), I just think we need to be able to use a generic one. We can call it `GenericConfig` or something.

**Comment by wilke** [comment]
This is not at all important for the current release since we are not using any of the codes in question for it and since the code has been moved out of improvlib this ticket can be closed, ok @jonesse3 ?

**Comment by wilke** [comment]
We should stop inventing names for stuff we have, b) is already your generic one.

**Comment by wilke** [comment]
Closing, deephyper is implementing a version of b.

**Comment by jonesse3** [comment]
@adpartin Please comment on this.
