### ISSUE TITLE
Add a section for global parameters

### ISSUE THREAD

**Issue by jonesse3** [JDACS4C-IMPROVE/IMPROVE#55]
The change can occur on line 33 in `config.py` per @wilke. Options are DEFAULT and GLOBAL. 
Vote to use GLOBAL as that makes more sense to me that it's applied everywhere. What do you think @adpartin? Once this has been fixed, I can add it to LGBM/framework-api and check that it's read.

**Comment by jonesse3** [comment]
Once we fix this issue, I can check with LGBM.

In particular, I'll check this: 

model_file_name = model
model_file_format = .txt
 
Per @nkoussa, this has to be repeated in both Train and Infer sections of the config file. May be better in Global. This flexibility could be useful.

**Comment by adpartin** [comment]
As I understand, global parameters are expected to be available in all three model scripts. @jonesse3 Is that correct? 
I'm trying to remember the discussion we had against using global parameters. I think the reason was making sure that these global params are printed in --help when we call each one of the relevant scripts. For example, we want param `model_file_name` to be printed when we type `python lgbm_train_improve.py --help` and `python lgbm_infer_improve.py --help`
@wilke @AlexandrNP do you remember?

**Comment by jonesse3** [comment]
Global parameters should theoretically be available for all 3 model scripts.

**Comment by wilke** [comment]
Just a fun fact. You can set global parameters for all sections in the INI Config file. Right now the implementaion uses the DEFAULT section for this. The original request was to rename DEFAULT to GLOBAL. Everything which is assigned in DEFAULT is available in the Preprocess, Train and Infer config

**Comment by adpartin** [comment]
Good to know.

**Comment by nkoussa** [comment]
Note: If you use the [DEFAULT] section you have to have section headers (like [Preprocess], [Train], [Infer]) or it doesn't work. Like you can't just put things in [DEFAULT] and delete the [Infer] section. So I'm only documenting using the three sections, I'm not documenting the DEFAULT section since this seems prone to error. Might as well leave it as DEFAULT and close the issue, IMO.

**Comment by adpartin** [comment]
**---  Not urgent  ---**

I see that we use `[DEFAULT]` section to set params in csa experiments, so I assume we'll use it in other workflows as well (e.g. deephyper HPO, parsl learning curves).

- Exp params for bruteforce csa: https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/workflows/bruteforce_csa/csa_bruteforce_params.ini
- Exp params for parsl csa: https://github.com/JDACS4C-IMPROVE/IMPROVE/blob/develop/workflows/parsl_csa/csa_params.ini

I think we should document this functionality in the context of workflow implementation rather than model curation; maybe in a README of the specific workflows (e.g., https://github.com/JDACS4C-IMPROVE/IMPROVE/tree/develop/workflows/bruteforce_csa)

I think it makes more sense to make it `[GLOBAL]`, but that's not urgent.
The behavior discussed in this issue is quite important, so let's keep it open for now.

**Comment by wilke** [comment]
Everyone is using DEFAULT  in their configs. So this issue is decided already.
